name: Rust Coverage

on:
  workflow_call:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          submodules: "true"

      - name: Checkout coverage scripts
        uses: actions/checkout@v7
        with:
          repository: ${{ job.workflow_repository }}
          ref: ${{ job.workflow_sha }}
          path: .shared
          sparse-checkout: |
            scripts/coverage

      - name: Use cache
        id: rust-cache
        uses: Swatinem/rust-cache@v2
        with:
          key: coverage

      - name: Update rustup
        if: steps.rust-cache.outputs.cache-hit != 'true'
        run: rustup update stable --no-self-update

      - name: Cache cargo-llvm-cov
        id: llvm-cov-cache
        uses: actions/cache@v6
        with:
          path: ~/.cargo/bin/cargo-llvm-cov
          key: cargo-llvm-cov-${{ runner.os }}-${{ runner.arch }}

      - name: Install cargo-llvm-cov
        if: steps.llvm-cov-cache.outputs.cache-hit != 'true'
        run: cargo install cargo-llvm-cov --locked

      - name: Generate coverage
        run: cargo llvm-cov --locked --workspace --json > /tmp/coverage.json

      - name: Coverage summary
        run: |
          echo "### Test Coverage Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          ./.shared/scripts/coverage/coverage_summary.sh < /tmp/coverage.json >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "<details><summary>Per-file coverage</summary>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          ./.shared/scripts/coverage/coverage_per_file.sh < /tmp/coverage.json >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY

      - name: Cleanup coverage
        if: always()
        run: rm -f /tmp/coverage.json